name: Build Reel

permissions:
  contents: write

on:
  push:
    # Run on any push (keeps it simple / reliable)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Build reel.mp4
        run: |
         set -e
         ls -1 public/videos/*.mp4 | sort | sed "s|^|file '|;s|$|'|" > videos.txt
         cat videos.txt
         rm -f public/reel.mp4

         ffmpeg -y -f concat -safe 0 -i videos.txt \
            -c:v libx264 -preset veryfast -crf 20 -pix_fmt yuv420p \
            -c:a aac -b:a 192k \
            -movflags +faststart \
         public/reel.mp4



      - name: Commit reel.mp4 (only if changed)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add public/reel.mp4

          # Only commit if there are changes
          if git diff --cached --quiet; then
            echo "No changes to reel.mp4; skipping commit."
            exit 0
          fi

          git commit -m "Update reel.mp4"
          git push
